# Generated by Django 3.0.5 on 2020-04-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20200426_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default='', upload_to='post/', verbose_name='Постер'),
        ),
    ]
