# Generated by Django 3.0.5 on 2020-04-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20200426_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comandmodel',
            name='player',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='comand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='News.ComandModel'),
        ),
    ]
