# Generated by Django 3.0.5 on 2020-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_auto_20200426_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название стрима')),
                ('date', models.DateField(verbose_name='Дата стрима')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка на стрим')),
            ],
            options={
                'verbose_name': 'Стрим',
                'verbose_name_plural': 'Стримы',
            },
        ),
    ]
