# Generated by Django 3.0.5 on 2020-04-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_auto_20200428_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamModel',
            new_name='LiveStreamModule',
        ),
    ]
