# Generated by Django 3.0.5 on 2020-04-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_auto_20200429_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestreammodule',
            options={'verbose_name': ':Живой стрим', 'verbose_name_plural': 'Живые стримы'},
        ),
        migrations.CreateModel(
            name='ArchivStreamModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название стрима')),
                ('name_chanel', models.CharField(max_length=150, verbose_name='Название канала')),
                ('date', models.DateField(verbose_name='Дата стрима')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка на стрим')),
                ('comand_name1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comand_1', to='News.ComandModel')),
                ('comand_name2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comand_2', to='News.ComandModel')),
                ('nameMatches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_name', to='News.MatchesModel')),
            ],
            options={
                'verbose_name': 'Архивный стрим',
                'verbose_name_plural': 'Архив стримов',
            },
        ),
    ]
