# Generated by Django 3.0.5 on 2020-04-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_auto_20200429_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivstreammodule',
            old_name='nameMatches',
            new_name='name_matches',
        ),
        migrations.AddField(
            model_name='matchesmodel',
            name='name_match',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Название матча'),
        ),
        migrations.AlterField(
            model_name='archivstreammodule',
            name='name_matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_name', to='News.MatchesModel'),
        ),
    ]
