# Generated by Django 3.0.5 on 2020-04-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0013_auto_20200429_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivstreammodule',
            name='name_matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_name', to='News.MatchesModel'),
        ),
    ]
