# Generated by Django 3.0.5 on 2020-04-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0014_auto_20200429_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivstreammodule',
            name='name_matches',
        ),
        migrations.RemoveField(
            model_name='livestreammodule',
            name='date',
        ),
    ]
