# Generated by Django 3.0.5 on 2020-04-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0016_auto_20200429_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название матча')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип матча')),
                ('prize_pool', models.SmallIntegerField(verbose_name='Призовой фонд')),
                ('description', models.TextField(max_length=500, verbose_name='Описание турнира')),
                ('comand', models.ManyToManyField(related_name='comand_tournament', to='News.ComandModel', verbose_name='Команды')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.AlterField(
            model_name='archivstreammodule',
            name='name_matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_name', to='News.TournamentModule'),
        ),
        migrations.AlterField(
            model_name='gamearchivmodel',
            name='name_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='News.TournamentModule'),
        ),
        migrations.DeleteModel(
            name='MatchesModule',
        ),
    ]
