# Generated by Django 3.0.5 on 2020-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0017_auto_20200429_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodule',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закончился'),
        ),
    ]
