# Generated by Django 3.0.5 on 2020-04-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0018_tournamentmodule_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodule',
            name='prize_pool',
            field=models.SmallIntegerField(default=0, verbose_name='Призовой фонд'),
        ),
    ]
