# Generated by Django 3.0.5 on 2020-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0019_auto_20200429_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivstreammodule',
            name='link',
            field=models.CharField(max_length=500, verbose_name='Ссылка на стрим'),
        ),
    ]
